plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
}

repositories {
    maven {
        name = "Terraformers"
        url = uri("https://maven.terraformersmc.com")
    }
}

apply from: rootProject.file('gradle/scripts/conditional-dependencies.gradle')

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    modImplementation "com.terraformersmc:modmenu:${project.fabric_modmenu_version}"

    conditionalModImplementation "fabric_jade_version", "curse.maven:jade-324717:${project.fabric_jade_version}"
    conditionalModImplementation "fabric_ftb_quests_version", "curse.maven:ftb-quests-fabric-438496:${project.fabric_ftb_quests_version}"
    conditionalModImplementation "fabric_ftb_library_version", "curse.maven:ftb-library-fabric-438495:${project.fabric_ftb_library_version}"
    conditionalModImplementation "fabric_ftb_teams_version", "curse.maven:ftb-teams-fabric-438497:${project.fabric_ftb_teams_version}"
    conditionalModImplementation "fabric_team_reborn_energy_version", "teamreborn:energy:${project.fabric_team_reborn_energy_version}"
    conditionalModImplementation "fabric_architectury_version", "curse.maven:architectury-api-419699:${project.fabric_architectury_version}"
}

loom {
    if (project(":common").file("src/main/resources/${mod_id}.accesswidener").exists()) {
        accessWidenerPath.set(project(":common").file("src/main/resources/${mod_id}.accesswidener"))
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}
