plugins {
    // see https://fabricmc.net/develop for new versions
    id 'fabric-loom' version '1.11-SNAPSHOT' apply false

    // see https://projects.neoforged.net/neoforged/moddevgradle for new versions
    id 'net.neoforged.moddev' version '2.0.107' apply false

    // see https://files.minecraftforge.net/net/minecraftforge/gradle/ForgeGradle for new versions
    // for some reason it doesn't work here, so it's moved to /forge/build.gradle
}
