### PROJECT
version=1.4.6
group=net.bivrik
java_version=21


### COMMON
mod_name=FancyToasts
mod_author=Bivrik
mod_id=fancytoasts
license=MIT
credits=Everyone. My friends, players, other people. Thank you all! If you want to actually behold peoples' names, check out Credits screen!
description=Redesigns the old advancement toast system, replacing it with a more attractive and interesting one.
issue_tracker_url=https://github.com/Bivrik/FancyToasts/issues
homepage_url=https://github.com/Bivrik
sources_url=https://github.com/Bivrik/FancyToasts


### MAIN
minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.22)
# https://maven.neoforged.net/releases/net/neoforged/neoform
neo_form_version=1.21.1-20240808.144430
# https://ldtteam.jfrog.io/ui/native/parchmentmc-public/org/parchmentmc/data
parchment_minecraft=1.21.1
parchment_version=2024.11.17


### FABRIC
# https://fabricmc.net/develop
fabric_version=0.116.6+1.21.1
fabric_loader_version=0.17.2
# https://www.curseforge.com/minecraft/mc-mods/modmenu/files/all
fabric_modmenu_version=11.0.3
# https://www.curseforge.com/minecraft/mc-mods/jade/files/all?gameVersionTypeId=4
fabric_jade_version=15.10.2+fabric
# https://www.curseforge.com/minecraft/mc-mods/ftb-quests-fabric/files/all
# https://www.curseforge.com/minecraft/mc-mods/ftb-library-fabric/files/all
# https://www.curseforge.com/minecraft/mc-mods/ftb-teams-fabric/files/all
# https://maven.fabricmc.net/teamreborn/energy
fabric_ftb_quests_version=7213964
fabric_ftb_library_version=7182153
fabric_ftb_teams_version=7209617
fabric_team_reborn_energy_version=4.1.0
# https://www.curseforge.com/minecraft/mc-mods/architectury-api/files/all
fabric_architectury_version=5786326


### FORGE
# https://files.minecraftforge.net/net/minecraftforge/forge
forge_version=52.1.0
forge_loader_version_range=[51,)
# https://www.curseforge.com/minecraft/mc-mods/jade/files/all?gameVersionTypeId=1
forge_jade_version=
# https://www.curseforge.com/minecraft/mc-mods/ftb-quests-forge/files/all?gameVersionTypeId=1
# https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge/files/all?gameVersionTypeId=1
# https://www.curseforge.com/minecraft/mc-mods/ftb-teams-forge/files/all?gameVersionTypeId=1
forge_ftb_quests_version=
forge_ftb_library_version=
forge_ftb_teams_version=
# https://www.curseforge.com/minecraft/mc-mods/architectury-api/files/all?gameVersionTypeId=1
forge_architectury_version=


### NEOFORGE
# https://neoforged.net
neoforge_version=21.1.209
neoforge_loader_version_range=[4,)
# https://www.curseforge.com/minecraft/mc-mods/jade/files/all?gameVersionTypeId=6
neoforge_jade_version=15.10.3+neoforge
# https://www.curseforge.com/minecraft/mc-mods/ftb-quests-forge/files/all?gameVersionTypeId=6
# https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge/files/all?gameVersionTypeId=6
# https://www.curseforge.com/minecraft/mc-mods/ftb-teams-forge/files/all?gameVersionTypeId=6
neoforge_ftb_quests_version=7260682
neoforge_ftb_library_version=7260617
neoforge_ftb_teams_version=7209616
# https://www.curseforge.com/minecraft/mc-mods/architectury-api/files/all?gameVersionTypeId=6
neoforge_architectury_version=5786327


### GRADLE
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
