### PROJECT
version=1.4.5
group=net.bivrik
java_version=17


### COMMON
mod_name=FancyToasts
mod_author=Bivrik
mod_id=fancytoasts
license=MIT
credits=Everyone. My friends, players, other people. Thank you all! If you want to actually behold peoples' names, check out Credits screen!
description=Redesigns the old advancement toast system, replacing it with a more attractive and interesting one.
issue_tracker_url=https://github.com/Bivrik/FancyToasts/issues
homepage_url=https://github.com/Bivrik
sources_url=https://github.com/Bivrik/FancyToasts


### MAIN
minecraft_version=1.20.1
minecraft_version_range=[1.20.1, 1.21)
# https://ldtteam.jfrog.io/ui/native/parchmentmc-public/org/parchmentmc/data
parchment_minecraft=1.20.1
parchment_version=2023.09.03


### FABRIC
# https://fabricmc.net/develop
fabric_version=0.92.2+1.20.1
fabric_loader_version=0.17.2
# https://www.curseforge.com/minecraft/mc-mods/modmenu/files/all
fabric_modmenu_version=7.0.1
# https://www.curseforge.com/minecraft/mc-mods/jade/files/all?gameVersionTypeId=4
fabric_jade_version=6291330
# https://www.curseforge.com/minecraft/mc-mods/ftb-quests-fabric/files/all
# https://www.curseforge.com/minecraft/mc-mods/ftb-library-fabric/files/all
# https://www.curseforge.com/minecraft/mc-mods/ftb-teams-fabric/files/all
# https://maven.fabricmc.net/teamreborn/energy
fabric_ftb_quests_version=7260735
fabric_ftb_library_version=6807422
fabric_ftb_teams_version=6130783
fabric_team_reborn_energy_version=3.0.0
# https://www.curseforge.com/minecraft/mc-mods/architectury-api/files/all
fabric_architectury_version=5137936


### FORGE
# https://files.minecraftforge.net/net/minecraftforge/forge
forge_version=47.2.30
forge_loader_version_range=[46,)
# https://www.curseforge.com/minecraft/mc-mods/jade/files/all?gameVersionTypeId=1
forge_jade_version=6855440
# https://www.curseforge.com/minecraft/mc-mods/ftb-quests-forge/files/all?gameVersionTypeId=1
# https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge/files/all?gameVersionTypeId=1
# https://www.curseforge.com/minecraft/mc-mods/ftb-teams-forge/files/all?gameVersionTypeId=1
forge_ftb_quests_version=7260736
forge_ftb_library_version=6807424
forge_ftb_teams_version=6130786
# https://www.curseforge.com/minecraft/mc-mods/architectury-api/files/all?gameVersionTypeId=1
forge_architectury_version=5137938


### GRADLE
org.gradle.jvmargs=-Xmx3G -Dnet.minecraftforge.gradle.check.certs=false
org.gradle.daemon=false
