plugins {
    id 'multiloader-loader'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'org.spongepowered.mixin' version '0.7-SNAPSHOT'
}

base {
    archivesName = "${mod_id}-forge-${minecraft_version}"
}

mixin {
    add sourceSets.main, "${mod_id}.refmap.json"

    config "${mod_id}.mixins.json"
}

jar {
    finalizedBy('reobfJar')
    manifest.attributes([
            "MixinConfigs": "${mod_id}.mixins.json"
    ])
}

dependencies {
    minecraft("net.minecraftforge:forge:${minecraft_version}-${forge_version}")
    annotationProcessor('org.spongepowered:mixin:0.8.5:processor')
    implementation('net.sf.jopt-simple:jopt-simple:5.0.4') { version { strictly '5.0.4' } }

    implementation(fg.deobf("curse.maven:jade-324717:${project.forge_jade_version}"))

    // Aether compatibility
    def aether_version = fg.deobf("maven.modrinth:aether:${project.forge_aether_version}")
    compileOnly(aether_version)
    if (project.aether_enable.toBoolean()) {
        runtimeOnly(aether_version)
        runtimeOnly(fg.deobf("maven.modrinth:curios:${project.forge_curios_api_version}"))
    }

    // FTB Quests compatibility
    def ftbquests_version = fg.deobf("curse.maven:ftb-quests-forge-289412:${project.forge_ftb_quests_version}")
    def ftblibrary_version = fg.deobf("curse.maven:ftb-library-forge-404465:${project.forge_ftb_library_version}")
    def architectury_version = fg.deobf("curse.maven:architectury-api-419699:${project.forge_architectury_version}")
    compileOnly(ftbquests_version)
    compileOnly(ftblibrary_version)
    compileOnly(architectury_version)
    if (project.ftbquests_enable.toBoolean()) {
        runtimeOnly(ftbquests_version)
        runtimeOnly(ftblibrary_version)
        runtimeOnly(architectury_version)
        runtimeOnly(fg.deobf("curse.maven:ftb-teams-forge-404468:${project.forge_ftb_teams_version}"))
    }
}

minecraft {
    mappings channel: 'official', version: minecraft_version
    copyIdeResources = true

    reobf = true // Forge 1.20.6+ uses official mappings at runtime, so we shouldn't reobf from official to SRG

    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformer = at
    }

    runs {
        client {
            workingDirectory file('runs/client')
            ideaModule "${rootProject.name}.${project.name}.main"
            taskName 'Client'
            mods {
                modClientRun {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory file('runs/server')
            ideaModule "${rootProject.name}.${project.name}.main"
            taskName 'Server'
            mods {
                modServerRun {
                    source sourceSets.main
                }
            }
        }

        data {
            workingDirectory file('runs/data')
            ideaModule "${rootProject.name}.${project.name}.main"
            args '--mod', mod_id, '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
            taskName 'Data'
            mods {
                modDataRun {
                    source sourceSets.main
                }
            }
        }
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'

publishing {
    publications {
        mavenJava(MavenPublication) {
            fg.component(it)
        }
    }
}

sourceSets.each {
    def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
    it.output.resourcesDir = dir
    it.java.destinationDirectory = dir
}