plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

apply from: rootProject.file('gradle/scripts/conditional-dependencies.gradle')

dependencies {
    conditionalImplementation "neoforge_jade_version", "maven.modrinth:jade:${project.neoforge_jade_version}"
    conditionalImplementation "neoforge_ftb_quests_version", "curse.maven:ftb-quests-forge-289412:${project.neoforge_ftb_quests_version}"
    conditionalImplementation "neoforge_ftb_library_version", "curse.maven:ftb-library-forge-404465:${project.neoforge_ftb_library_version}"
    conditionalImplementation "neoforge_ftb_teams_version", "curse.maven:ftb-teams-forge-404468:${project.neoforge_ftb_teams_version}"
    conditionalImplementation "neoforge_architectury_version", "curse.maven:architectury-api-419699:${project.neoforge_architectury_version}"
}

neoForge {
    version = neoforge_version
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.add(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})"
        }
        client {
            client()
        }
        data {
            clientData()
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }
