plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

dependencies {
    implementation "maven.modrinth:jade:${project.neoforge_jade_version}"

    // Aether compatibility
    def aether_version = "maven.modrinth:aether:${project.neoforge_aether_version}"
    compileOnly(aether_version)
    if (project.aether_enable.toBoolean()) {
        runtimeOnly(aether_version)
        runtimeOnly("maven.modrinth:accessories:${project.neoforge_accessories_version}")
        runtimeOnly("maven.modrinth:owo-lib:${project.neoforge_owo_version}")
    }

    // FTB Quests compatibility
    def ftbquests_version = "curse.maven:ftb-quests-forge-289412:${project.neoforge_ftb_quests_version}"
    def ftblibrary_version = "curse.maven:ftb-library-forge-404465:${project.neoforge_ftb_library_version}"
    def architectury_version = "curse.maven:architectury-api-419699:${project.neoforge_architectury_version}"
    compileOnly(ftbquests_version)
    compileOnly(ftblibrary_version)
    compileOnly(architectury_version)
    if (project.ftbquests_enable.toBoolean()) {
        runtimeOnly(ftbquests_version)
        runtimeOnly(ftblibrary_version)
        runtimeOnly(architectury_version)
        runtimeOnly("curse.maven:ftb-teams-forge-404468:${project.neoforge_ftb_teams_version}")
    }

    // Questlog compatibility
    def questlog_version = "maven.modrinth:questlog:${project.neoforge_questlog_version}"
    compileOnly(questlog_version)
    if (project.questlog_enable.toBoolean()) {
        runtimeOnly(questlog_version)
        runtimeOnly("maven.modrinth:cloth-config:${project.neoforge_cloth_config_version}")
    }
}

neoForge {
    version = neoforge_version

    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }

    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }

    runs {
        configureEach {
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
        }
        client {
            client()
            gameDirectory = project.file('runs/client')
        }
        server {
            server()
            gameDirectory = project.file('runs/server')
        }
        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
            gameDirectory = project.file('runs/data')
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }
